swagger: "2.0"
info:
  version: v1.0.0
  title: "Terminal 101: Flight"
  description: Terminal 101 - Flight service
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

host: test-terminal101-flight.herokuapp.com
# host: localhost:8005
basePath: /

tags:
  - name: Airport
    description: Airport routes
  - name: Book
    description: Book flight and booked flights routes
  - name: City
    description: City routes
  - name: Country
    description: Country routes
  - name: Flight
    description: Flight routes
  - name: Restriction
    description: Country/City Restriction Conditions
  - name: Waypoint
    description: Flight origin/destination points

paths:
  # NOTE: Airport
  /country/{countryCode}/city/{cityCode}/airport:
    # NOTE: Get all airports of city of country
    get:
      tags:
        - Airport
      description: Get all airports of a city.
      parameters:
        - name: countryCode
          in: path
          type: string
          required: true
          value: DE
          description: Country standard code
        - name: cityCode
          in: path
          required: true
          type: string
          value: MUC
          description: City standard code
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Airport"

  # NOTE: City
  /country/{countryCode}/city:
    # NOTE: Get all cities of country
    get:
      tags:
        - City
      description: Get all cities of a country.
      parameters:
        - name: countryCode
          in: path
          type: string
          required: true
          value: DE
          description: Country standard code
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/City"

  # NOTE: Country
  /country:
    # NOTE: Get all countries
    get:
      tags:
        - Country
      description: Get all countries.
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Country"

  # NOTE: Waypoint
  /waypoint/{waypointType}:
    # NOTE: Get waypoints for origin/destination
    get:
      tags:
        - Waypoint
      description: Get autocomplete value list.
      parameters:
        - name: waypointType
          in: path
          type: string
          enums: [ORIGIN, DESTINATION]
          required: true
          value: ORIGIN
        - name: keyword
          in: query
          type: string
          value: MUC
          description: Keyword for search.
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Waypoint"

  /waypoint/{waypointType}/popular:
    # NOTE: Get popular waypoints
    get:
      tags:
        - Waypoint
      description: Get popular waypoints.
      parameters:
        - name: waypointType
          in: path
          type: string
          enums: [ORIGIN, DESTINATION]
          required: true
          value: ORIGIN
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              type: object
              $ref: "#/definitions/WaypointCount"

  # NOTE: Flight
  /flight/search:
    # NOTE: Search a fligh
    get:
      tags:
        - Flight
      description: Search a flight
      parameters:
        - name: origin
          in: query
          type: string
          required: true
          value: MUC
          description: Flight origin code.
        - name: destination
          in: query
          type: string
          required: true
          value: WDC
          description: Flight destination code.
        - name: departureDate
          in: query
          type: string
          required: true
          value: "2022-01-20"
          description: Flight departure date.
        - name: returnDate
          in: query
          type: string
          required: false
          value: "2022-02-5"
          description: Flight return date.
        - name: adults
          in: query
          type: number
          required: false
          value: 1
          description: Travelers adults count (Default equals 1).
        - name: children
          in: query
          type: number
          required: false
          description: Travelers children count (Default equals 0).
        - name: infants
          in: query
          type: number
          required: false
          description: Travelers infants count (Default equals 0).
        - name: travelClass
          in: query
          type: string
          enum: [ECONOMY, PREMIUM_ECONOMY, BUSINESS, FIRST]
          required: false
          description: Default is ECONOMY class.
        - name: segments
          in: query
          type: array
          required: false
          value:
            - DUB:NYC:2022-02-01
            - BKK:IST:2022-02-03
          items:
            type: string
          description: Keyword for search.
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Flight"

  /flight/search/{searchId}/limits:
    # NOTE: Get popular flights
    get:
      tags:
        - Flight
      parameters:
        - name: searchId
          in: path
          required: true
          type: string
      description: Get filter limits for a search.
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/FilterLimit"

  /flight/search/{searchId}:
    # NOTE: Get popular flights
    get:
      tags:
        - Flight
      parameters:
        - name: searchId
          in: path
          required: true
          type: string
        - name: stops
          in: query
          required: false
          type: array
          items:
            type: number
        - name: airports
          in: query
          required: false
          type: array
          items:
            type: string
        - name: airlines
          in: query
          required: false
          type: array
          items:
            type: string
        - name: priceFrom
          in: query
          required: false
          type: number
        - name: priceTo
          in: query
          required: false
          type: number
        - name: departureTimeFrom
          in: query
          required: false
          type: number
        - name: departureTimeTo
          in: query
          required: false
          type: number
        - name: arrivalTimeFrom
          in: query
          required: false
          type: number
        - name: arrivalTimeTo
          in: query
          required: false
          type: number
        - name: durationFrom
          in: query
          required: false
          type: number
        - name: durationTo
          in: query
          required: false
          type: number
      description: Get search by code and filter that.
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Flight"

  /flight/search/{searchId}/details/{flightIndex}:
    # NOTE: Get popular flights
    get:
      tags:
        - Flight
      parameters:
        - name: searchId
          in: path
          required: true
          type: string
        - name: flightIndex
          in: path
          required: true
          type: string
      description: Get specific flight.
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/Flight"

  /flight/popular:
    # NOTE: Get popular flights
    get:
      tags:
        - Flight
      description: Get popular flights.
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/FlightPopular"

  /restriction/{countryCode}/{cityCode}:
    # NOTE: Restriction conditions
    get:
      tags:
        - Restriction
      description: Country/City restriction conditions
      parameters:
        - name: countryCode
          in: path
          required: true
          type: string
          example: US
          value: US
        - name: cityCode
          in: path
          required: false
          type: string
      responses:
        "200":
          description: OK

  /flight/book:
    # NOTE: Get all booked flights list
    get:
      tags:
        - Book
      description: Get all booked flights list
      parameters:
        - name: Authorization
          in: header
          type: string
          value: Bearer
          required: true
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/BookedFlightDetails"

    # NOTE: Book flight
    post:
      tags:
        - Book
      description: Book flight
      parameters:
        - name: Authorization
          in: header
          type: string
          value: Bearer
          required: true
        - name: Flight Info
          in: body
          required: true
          schema:
            $ref: "#/definitions/BookFlightInfo"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/BookFlightResult"

definitions:
  Flight:
    required:
      - origin
      - destination
      - time
    properties:
      origin:
        type: string
        example: MUC
      destination:
        type: string
        example: NYC
      time:
        type: string
        example: "2022-01-13T12:15:00.000Z"

  FilterLimit:
    properties:
      stops:
        type: array
        items:
          type: number
      aircrafts:
        type: array
        items:
          type: string
      airports:
        type: array
        items:
          $ref: "#/definitions/Waypoint"
      airlines:
        type: array
        items:
          $ref: "#/definitions/Waypoint"
      price:
        $ref: "#/definitions/NumberRange"
      departureTime:
        $ref: "#/definitions/NumberRange"
      arrivalTime:
        $ref: "#/definitions/NumberRange"
      duration:
        $ref: "#/definitions/NumberRange"

  FlightPopular:
    required:
      - origin
      - destination
      - time
      - count
    properties:
      origin:
        $ref: "#/definitions/Waypoint"
      destination:
        $ref: "#/definitions/Waypoint"
      time:
        type: string
        example: "2022-01-13T12:15:00.000Z"
      count:
        type: number
        example: 13

  WaypointCount:
    required:
      - code
      - name
      - description
      - count
    properties:
      code:
        type: string
        example: MUC
      name:
        type: string
        example: Munchen
      description:
        type: string
        example: Munchen airport
      count:
        type: number
        example: 10

  Waypoint:
    required:
      - code
      - name
      - description
    properties:
      code:
        type: string
        example: MUC
      name:
        type: string
        example: Munchen
      description:
        type: string
        example: Munchen airport

  Airport:
    required:
      - code
      - name
    properties:
      code:
        type: string
        example: MUC
      name:
        type: string
        example: Munchen

  City:
    required:
      - code
      - name
    properties:
      code:
        type: string
        example: MUC
      name:
        type: string
        example: Munchen

  Country:
    required:
      - code
      - name
    properties:
      code:
        type: string
        example: MUC
      name:
        type: string
        example: Munchen
      dialingCode:
        type: number
        example: 123

  NumberRange:
    properties:
      min:
        type: number
        example: 0
      max:
        type: number
        example: 1000

  BookedFlightDetails:
    properties:
      code:
        type: string
        example: fw3r879fyh24ry7yf
      bookedBy:
        type: string
        example: 231f234rfh34yhf32y
      status:
        type: string
        enum: [PAYING, INPROGRESS, REFUND, CANCEL, REMOVE, BOOKED, REJECTED]
        example: PAYING
      time:
        type: string
        example: 2022-02-05
      passengers:
        type: array
        items:
          $ref: "#/definitions/BookFlightPassenger"
      origin:
        $ref: "#/definitions/Waypoint"
      destination:
        $ref: "#/definitions/Waypoint"
      travelClass:
        type: string
        enum: [ECONOMY, PERMIUM_ECONOMY, BUSINESS, FIRST]
        example: ECONOMY
      price:
        type: number
        example: 234

  BookFlightInfo:
    required:
      - searchedFlightCode
      - flightDetailsCode
      - paymentMethodName
    properties:
      searchedFlightCode:
        type: string
        example: asdfhkadfhdksaa
      flightDetailsCode:
        type: number
        example: 2
      paymentMethodName:
        type: string
        example: credit-card
      payWay:
        type: string
        enum: [PAY, WALLET]
        example: WALLET
      passengers:
        type: array
        items:
          $ref: "#/definitions/BookFlightPassenger"

  BookFlightResult:
    properties:
      code:
        type: string
        example: asdfhkadfhdksaa
      type:
        type: string
        enum: [PAY, TRANSFER_TO, TRANSFER_FROM, DEPOSIT]
        example: DEPOSIT
      value:
        type: number
        example: 100
      credit:
        type: number
        example: 1000
      time:
        type: string
        example: 2022-02-25
      description:
        type: string
        example: Pay for book flight's ticket
      externalTransactionId:
        type: string
        example: askjfh23h31i2uyuf93h4ifyh78934y3i

  BookFlightPassenger:
    required:
      - documentCode
      - documentIssuedAt
    properties:
      documentCode:
        type: string
        example: 231aweiW2
      documentIssuedAt:
        type: string
        example: Germany

schemes:
  # - http
  - https
consumes:
  - application/json
produces:
  - application/json
