swagger: '2.0'
info:
  version: v1.0.0
  title: 'Terminal 101: Flight'
  description: Terminal 101 - Flight service
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

host: test-terminal101-flight.herokuapp.com
# host: localhost:8005
basePath: /

tags:
  - name: Airport
    description: Airport routes
  - name: City
    description: City routes
  - name: Country
    description: Country routes
  - name: Flight
    description: Flight routes
  - name: Waypoint
    description: Flight origin/destination points

    
paths:
# NOTE: Airport
  /country/{countryCode}/city/{cityCode}/airport:
# NOTE: New setting
    get:
      tags:
        - Airport
      description: Get all airports of a city.
      parameters:
        - name: countryCode
          in: path
          type: string
          required: true
          value: DE
          description: Country standard code
        - name: cityCode
          in: path
          required: true
          type: string
          value: MUC
          description: City standard code
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Airport'

# NOTE: City
  /country/{countryCode}/city:
# NOTE: New setting
    get:
      tags:
        - City
      description: Get all cities of a country.
      parameters:
        - name: countryCode
          in: path
          type: string
          required: true
          value: DE
          description: Country standard code
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/City'

# NOTE: Country
  /country:
# NOTE: New setting
    get:
      tags:
        - Country
      description: Get all countries.
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Country'

# NOTE: Waypoint
  /waypoint/{waypointType}:
# NOTE: New setting
    get:
      tags:
        - Waypoint
      description: Get autocomplete value list.
      parameters:
        - name: waypointType
          in: path
          type: string
          enums: [ORIGIN, DESTINATION]
          required: true
          value: ORIGIN
        - name: keyword
          in: query
          type: string
          required: true
          value: MUC
          description: Keyword for search.
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Waypoint'

  /waypoint/{waypointType}/popular:
# NOTE: New setting
    get:
      tags:
        - Waypoint
      description: Get popular waypoints.
      parameters:
        - name: waypointType
          in: path
          type: string
          enums: [ORIGIN, DESTINATION]
          required: true
          value: ORIGIN
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/WaypointPopular'

# NOTE: Flight
  /flight:
# NOTE: New setting
    get:
      tags:
        - Flight
      description: Get autocomplete value list.
      parameters:
        - name: origin
          in: query
          type: string
          required: true
          value: MUC
          description: Keyword for search.
        - name: destination
          in: query
          type: string
          required: true
          value: WDC
          description: Keyword for search.
        - name: return
          in: query
          type: boolean
          required: false
          # value: false
          description: Keyword for search.
        - name: segments
          in: query
          type: array
          required: false
          value:
            - NYC
            - IST
          items:
            type: string
          description: Keyword for search.
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Flight'

  /flight/popular:
# NOTE: New setting
    get:
      tags:
        - Flight
      description: Get popular waypoints.
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/FlightPopular'


definitions:
  Flight:
    required:
      - origin
      - destination
      - time
    properties:
      origin:
        type: string
        example: MUC
      destination:
        type: string
        example: NYC
      time:
        type: string
        example: "2022-01-13T12:15:00.000Z"

  FlightPopular:
    required:
      - origin
      - destination
      - time
      - count
    properties:
      origin:
        type: string
        example: MUC
      destination:
        type: string
        example: NYC
      time:
        type: string
        example: "2022-01-13T12:15:00.000Z"
      count:
        type: number
        example: 13

  WaypointPopular:
    required:
      - code
      - count
    properties:
      code:
        type: string
        example: MUC
      count:
        type: number
        example: 10

  Waypoint:
    required:
      - code
      - name
    properties:
      code:
        type: string
        example: MUC
      name:
        type: string
        example: Munchen

  Airport:
    required:
      - code
      - name
    properties:
      code:
        type: string
        example: MUC
      name:
        type: string
        example: Munchen

  City:
    required:
      - code
      - name
    properties:
      code:
        type: string
        example: MUC
      name:
        type: string
        example: Munchen

  Country:
    required:
      - code
      - name
    properties:
      code:
        type: string
        example: MUC
      name:
        type: string
        example: Munchen

schemes:
  # - http
  - https
consumes:
  - application/json
produces:
  - application/json
