swagger: '2.0'
info:
  version: v1.0.0
  title: 'Terminal 101: Flight'
  description: Terminal 101 - Flight service
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
host: test-terminal101-flight.herokuapp.com
basePath: /
tags:
  - name: Airport
    description: Airport lists
  - name: City
    description: Country's cities
  - name: Country
    description: All countries list
  - name: Waypoint
    description: Flight origin/destination points

    
paths:
# NOTE: Airport
  /country/{countryCode}/city/{cityCode}/airport:
# NOTE: New setting
    get:
      tags:
        - Airport
      description: Get all airports of a city.
      parameters:
        - name: countryCode
          in: path
          type: string
          required: true
          value: DE
          description: Country standard code
        - name: cityCode
          in: path
          required: true
          type: string
          value: MUC
          description: City standard code
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Airport'

# NOTE: City
  /country/{countryCode}/city:
# NOTE: New setting
    get:
      tags:
        - City
      description: Get all cities of a country.
      parameters:
        - name: countryCode
          in: path
          type: string
          required: true
          value: DE
          description: Country standard code
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/City'

# NOTE: Country
  /country:
# NOTE: New setting
    get:
      tags:
        - Country
      description: Get all countries.
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Country'

# NOTE: Waypoint
  /waypoint/{waypointType}:
# NOTE: New setting
    get:
      tags:
        - Waypoint
      description: Get autocomplete value list.
      parameters:
        - name: waypointType
          in: path
          type: string
          enums: [ORIGIN, DESTINATION]
          required: true
          value: ORIGIN
        - name: keyword
          in: query
          type: string
          required: true
          value: MUC
          description: Keyword for search.
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Country'


definitions:
  Airport:
    required:
      - code
      - name
    properties:
      code:
        type: string
        example: MUC
      name:
        type: string
        example: Munchen

  City:
    required:
      - code
      - name
    properties:
      code:
        type: string
        example: MUC
      name:
        type: string
        example: Munchen

  Country:
    required:
      - code
      - name
    properties:
      code:
        type: string
        example: MUC
      name:
        type: string
        example: Munchen

schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
