name: Account Project CLI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Copy .env file
      run: |
         cp /var/www/terminal101/terminal101_back/terminal101.backend.account/_work/terminal101.backend.account/tmpfiles/.env /var/www/terminal101/terminal101_back/terminal101.backend.account/_work/terminal101.backend.account/terminal101.backend.account/
         echo Copied
    - run: |
        echo "Install Packages"
        npm i
        pm2 stop Account
        pm2 start Account
        pm2 save 
        sudo service nginx restart
        echo "Finish"
