name: Flight Production CLI

on: 
  push:
    branches: [production]
  pull_request:
    branches: [production]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Copy .env file
      run: |
         cp /var/www/terminal101/terminal101_back/terminal101.backend.flight/_work/Terminal101.Backend.Flight/tmpfiles/.env /var/www/terminal101/terminal101_back/terminal101.backend.flight/_work/Terminal101.Backend.Flight/Terminal101.Backend.Flight/
         echo Copied
    - run: |
        echo "Install Packages"
        npm i
        pm2 stop Flight
        pm2 start Flight
        pm2 save 
        sudo service nginx restart
        echo "Finish"
